voiceworks_domo:
    resource: "@VoiceworksDomoBundle/Controller/"
    type:     annotation
    prefix:   /

# AcmeDemoBundle routes (to be removed)
_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"
    prefix: /demo

_cmf_create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
